steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "SERVICE_URL=${_SERVICE_URL}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest"

substitutions:
  _SERVICE_URL: ""
  _REGION: "asia-northeast1"
  _SERVICE_NAME: "shop-mcp"
